# .github/workflows/ci-cd-yandex-cloud.yml
name: CI/CD to Yandex Cloud

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd payment_service
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          cd payment_service
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/unit/ -v --tb=short

  build-and-push-to-yc:
    runs-on: ubuntu-latest
    needs: test  # Ждем завершения тестов
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/payment_service:latest

      - name: Login to YC Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Verify login
        run: |
          echo "=== Login Verification ==="
          cat ~/.docker/config.json | grep cr.yandex || echo "Not logged in to YC Registry"

      - name: Push image to YC Registry
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/payment_service:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-push-to-yc]
    steps:
      - name: Debug YC permissions
        run: |
          echo "=== Testing Yandex Cloud access ==="
          echo "Folder ID: ${{ secrets.YC_FOLDER_ID }}"
          echo "Container: ${{ secrets.YC_CONTAINER_NAME }}"
          echo "SA ID: ${{ secrets.YC_SA_ID }}"
          
          # Попробуем проверить доступ к Container Registry
          docker pull cr.yandex/${{ secrets.YC_REGISTRY_ID }}/payment_service:latest || echo "Cannot pull image"

      - name: Deploy serverless container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/payment_service:latest
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
#          revision-env: |
#            AMQP_URL=${{ secrets.ENV_AMQP_URL }}
#            POSTGRES_URL=${{ secrets.ENV_POSTGRES_URL }}